<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_1_of_100_days.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 01. Array Creation

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


In [3]:
array_2d= np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
array_zeros = np.zeros((2, 3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
array_ones = np.ones((2, 3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
array_eye= np.eye(3)
print(array_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
array_full_8= np.full((2, 3), 8)
print(array_full_8)

[[8 8 8]
 [8 8 8]]


In [9]:
array_with_arrange = np.arange(0, 10, 2)
print(array_with_arrange)

[0 2 4 6 8]


In [10]:
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
random_float=np.random.rand(3,4)
random_float

array([[0.35613088, 0.27398482, 0.17160486, 0.38604934],
       [0.32617784, 0.83728561, 0.84001612, 0.93328034],
       [0.26426153, 0.77825844, 0.33356176, 0.70924528]])

In [12]:
random_int=np.random.randint(1,10,size=(3,4))
random_int

array([[4, 7, 2, 4],
       [1, 4, 7, 5],
       [1, 1, 8, 9]])

## 2. Array Characteristics

In [13]:
array_1d.shape

(5,)

In [14]:
array_2d.ndim

2

In [15]:
array_3d.size # Total number of elements

8

In [16]:
random_float.dtype

dtype('float64')

In [17]:
# Memory
array_1d.nbytes

40

In [18]:
type(array_2d)

numpy.ndarray

## 3. Mathematical Operations

In [19]:
mat_A = np.array([[1, 2], [3, 4]])
mat_B = np.array([[5, 6], [7, 8]])

mat_mul = np.matmul(mat_A, mat_B)
print(mat_mul)

[[19 22]
 [43 50]]


In [20]:
# Element wise

mat_A * mat_B

array([[ 5, 12],
       [21, 32]])

In [21]:
# Transpose

mat_A.T

array([[1, 3],
       [2, 4]])

In [22]:
# inverse

np.linalg.inv(mat_A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
# determint

np.linalg.det(mat_A)

np.float64(-2.0000000000000004)

In [24]:
eigenval, eigenvec = np.linalg.eig(mat_A)
print(eigenval)
print(eigenvec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 4. Statistics

In [26]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
mean = np.mean(array_2d,axis=0) # 0 column
print(mean)

[2.5 3.5 4.5]


In [27]:
median = np.median(array_2d,axis=1) # 1 row
print(median)

[2. 5.]


In [28]:
# Standard Deviations

In [29]:
Std_dev = np.std(array_2d)
print(Std_dev)

1.707825127659933


In [30]:
variance=np.var(array_2d)
print(variance)

2.9166666666666665


In [31]:
min = np.min(array_2d)
print(min)

1


In [32]:
max= np.max(array_2d)
print(max)

6


In [33]:
# cumulative sum

cum_sum = np.cumsum(array_2d)
print(cum_sum)

[ 1  3  6 10 15 21]


## 5. Reshape

In [34]:
reshape_1d = np.array([1, 2, 3, 4, 5, 6])
reshape_2d = reshape_1d.reshape(2, 3)
print(reshape_2d)

[[1 2 3]
 [4 5 6]]


In [35]:
# 2d to 1d
flattened=reshape_2d.ravel()
print(flattened)

[1 2 3 4 5 6]


In [36]:
array_1d

array([1, 2, 3, 4, 5])

In [37]:
slice_1d = array_1d[1:4]
slice_1d

array([2, 3, 4])

In [38]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
slice_2d = array_2d[:, 1:]
slice_2d

array([[2, 3],
       [5, 6]])

In [40]:
slice_2d = array_2d[1:, :]
slice_2d

array([[4, 5, 6]])