<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/numpy_06_07_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A= np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

01  Find positions where both array have similar element

In [3]:
result = np.where(A==B)
print(result)

(array([1, 3, 5, 7]),)


02 Changing column values

In [5]:
Array_A = np.arange(9).reshape(3,3)
Array_A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# Changing column with array A

Array_A = Array_A[:,[1,0,2]]

In [7]:
Array_A

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

03 reversing the values of rows in 2D

In [8]:
Array_A = Array_A[::-1,:]

In [9]:
Array_A

array([[7, 6, 8],
       [4, 3, 5],
       [1, 0, 2]])

04 create an array of 2 x 4, random values from 5 to 9

In [10]:
Array_random= np.random.randint(5,10,size=(2,4))
Array_random

array([[9, 8, 8, 9],
       [6, 6, 5, 8]])

In [11]:
# Another Way in float values
Array_random= np.random.uniform(5,10,size=(2,4))
Array_random

array([[6.70084993, 6.25008494, 6.92392508, 7.12499351],
       [6.59801522, 6.8286641 , 8.65835922, 7.39154196]])

In [12]:
Array_rand_int= np.random.randint(5,10,size=(3,3))
Array_rand_int

array([[6, 9, 8],
       [7, 7, 8],
       [5, 7, 8]])

In [13]:
Array_rand_int=Array_rand_int[np.sum(Array_rand_int,axis=1) > 17]

In [14]:
Array_rand_int

array([[6, 9, 8],
       [7, 7, 8],
       [5, 7, 8]])

In [15]:
Array_rand_int=Array_rand_int[np.sum(Array_rand_int,axis=1) > 19]

In [16]:
Array_rand_int

array([[6, 9, 8],
       [7, 7, 8],
       [5, 7, 8]])

05 Eulidian distance

In [17]:
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])

euclidean_distance = np.linalg.norm(A-B)

In [18]:
euclidean_distance

np.float64(6.708203932499369)