<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_for_Pandas_1_of_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Array Creation

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d

array([1, 2, 3, 4, 5])

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
zeros_arr = np.zeros((2, 3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones_arr = np.ones((2, 3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arange_arr = np.arange(1, 10)
arange_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
linspace_arr = np.linspace(1, 10, 5)
linspace_arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Array Details

In [8]:
zeros_arr.shape

(2, 3)

In [9]:
zeros_arr.ndim

2

In [10]:
ones_arr.dtype

dtype('float64')

In [11]:
arr_2d.size

6

## Array Reshaping

In [12]:
arr_2d_reshaped = arr_2d.reshape(3, 2)
arr_2d_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr_2d_flattened = arr_2d.flatten()
arr_2d_flattened

array([1, 2, 3, 4, 5, 6])

## Mathematical operations

In [14]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr_2d_clip_divide= np.clip(arr_2d, 2, 4) # value smaller than 2 becomes 2
arr_2d_clip_divide # value larger than 4 become 4

array([[2, 2, 3],
       [4, 4, 4]])

In [16]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [17]:
add_2_arrays = arr1 + arr2
add_2_arrays

sub_2_arrays = arr1 - arr2
sub_2_arrays

mul_2_arrays = arr1 * arr2
mul_2_arrays

div_2_arrays = arr1 / arr2
div_2_arrays

dot_2_arrays = np.dot(arr1, arr2)
dot_2_arrays

array([[19, 22],
       [43, 50]])

## Statistical Functions

In [18]:
nums= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(nums)
mean

np.float64(5.5)

In [19]:
median= np.median(nums)
median

np.float64(5.5)

In [20]:
std = np.std(nums) # Standard Deviations
std

np.float64(2.8722813232690143)

In [21]:
sum = np.sum(nums)
sum

np.int64(55)

In [22]:
min = np.min(nums)
min

np.int64(1)

In [23]:
max = np.max(nums)
max

np.int64(10)

## Indexing and Slicing

In [24]:
arr_2d= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# First Row
arr_2d[0]

array([1, 2, 3])

In [26]:
# First element

arr_2d[0][0]

np.int64(1)

In [27]:
arr_2d[1,1] # Printing 5

np.int64(5)

In [28]:
new_arr = arr_2d[1:, 1:]
new_arr

array([[5, 6],
       [8, 9]])

In [30]:
new_arr = arr_2d[:2, :2]
new_arr

array([[1, 2],
       [4, 5]])

## Logical Operations

In [31]:
masking = arr_2d > 5

In [32]:
masking

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [33]:
# Lets filter based on mask

new_arr_mask = arr_2d[masking]
new_arr_mask

array([6, 7, 8, 9])

## Random Data

In [34]:
rand_arr = np.random.rand(3, 3)
rand_arr

array([[0.37853449, 0.6051398 , 0.46851243],
       [0.82083966, 0.04801871, 0.02025061],
       [0.81519254, 0.87422762, 0.576722  ]])

In [35]:
np.random.randint(1, 10, (3, 3))

array([[4, 3, 8],
       [5, 7, 3],
       [8, 3, 2]])

In [36]:
rand_arr = np.random.rand(3, 3)
rand_arr

array([[0.01884207, 0.97046455, 0.02091622],
       [0.57896218, 0.59497089, 0.22281328],
       [0.36147917, 0.74780314, 0.61981468]])