<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/NumPy_10_06%2C2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# N-D Array

In [2]:
nums = [[y for y in range(y+1,y+5)] for y in range(0,8,4)]

nums

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [3]:
import numpy as np

arr = np.array(nums)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


### 3D array making from 2 2D array (3 rows and 4 cols)

In [6]:
newArr = np.array([[[1, 2, 3, 4], #3D array
 [5, 6, 7, 8],
 [9, 10, 11, 12]],
  [[13, 14, 15, 16],
 [17, 18, 19, 20],
 [21, 22, 23, 24]]])

print(newArr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


#Array Creation from Scratch



```
np.zeros()
np.ones()
np.arrange()
np.random.rand()
```



In [7]:
# 0 array of 2 rows and 3 cols

print(np.zeros((2,3)))

print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(np.zeros((2,2,3)))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


### We can create a N-D array of a specfic value

In [10]:
num_arr_5 = np.full((2,2),7)
print(num_arr_5)

[[7 7]
 [7 7]]


### Random N-D array

In [11]:
rand_arr = np.random.rand(2,3)
print(rand_arr)

[[0.4314554  0.34741521 0.38012733]
 [0.78413349 0.80747726 0.78853819]]


In [12]:
# 3D ramdom array

rand_arr_3d = np.random.rand(2,2,3)
print(rand_arr_3d)

[[[0.05694794 0.6185712  0.42535835]
  [0.74681044 0.44912274 0.36612595]]

 [[0.5524689  0.001043   0.15952942]
  [0.43618938 0.08935102 0.21904968]]]


### numpy empty array

In [13]:
# Empty are used to later fill up and comes with garbage values
empty_arr = np.empty((2,3))
print(empty_arr)

[[0.4314554  0.34741521 0.38012733]
 [0.78413349 0.80747726 0.78853819]]
