<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the Numpy and check version

In [4]:
import numpy as np
print(np.__version__)

2.0.2


# Creating numpy arrays

In [19]:
a = np.array([1,2,3]) # normal array
b = np.zeros((2,3)) # 2 rows and 3 cols, filled by 0
c=np.ones((3,3)) # 3 rows and 3 cols filled by 1
print("Value Of A: ",a)
print("Value Of B:\n",b)
print("Value Of C:\n",c)

Value Of A:  [1 2 3]
Value Of B:
 [[0. 0. 0.]
 [0. 0. 0.]]
Value Of C:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Eye, arrange, linspace

In [11]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
print(np.arange(10)) # from 0-9 max: 10

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(np.linspace(0,1,6)) # dividing 0-1 in 6 parts

[0.  0.2 0.4 0.6 0.8 1. ]


# Index and slicing

In [20]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[0,1]) # Row 0, col 1

20


In [22]:
print(arr[:,1]) # column 1

[20 50]


In [23]:
print(arr[1,:2]) # row 1 and col 0 and 1

[40 50]


# Array Math and Operations

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)

print(np.dot(a,b)) # 1*4+2*5+3*6 (Row multiply with col)

[5 7 9]
[ 4 10 18]
32


# Boolean Indexing and Filtering

In [26]:
arr = np.array([1,5,7,9,2])
print(arr[arr>5]) # where array element should be less that 5

[7 9]


# Aggregations and statistics

In [28]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))

24


In [31]:
print(np.mean(arr,axis=0))

4.8


# Reshape and stack and Spilt

In [38]:
arr = np.arange(12)
print(arr)
reshaped = arr.reshape((3,4)) # 3 row, 4 col
print(reshaped)
v_stack = np.vstack([arr, arr]) # stack as a row
print(v_stack)
h_spilt = np.hsplit(reshaped,2) # stack as a row
print(h_spilt)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
