<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/NumPy_09_06%2C2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array Creation

In [1]:
import numpy as np

# Python List to NumPy array

nums = [x for x in range(5)]
numpy_array = np.array(nums)

print(numpy_array)

[0 1 2 3 4]


In [2]:
#Lets use directly

numpy_array = np.array([x for x in range(5)])

print(numpy_array)

[0 1 2 3 4]


## np zeros

In [5]:
np_zeros_1D = np.zeros(5)
np_zeros_2D = np.zeros([2,3])

np_zeros_1D, np_zeros_2D

(array([0., 0., 0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

##np arrange

is like python range

In [7]:
val_0_5 = np.arange(5) # In python we write like range(5)
val_1_9_step_1 = np.arange(1,6,1) # In python we write like range(1,6,1)

val_0_5, val_1_9_step_1


(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

##Random Rand

In [8]:
# Lets create 5 random numbers

random_array = np.random.rand(5)
print(random_array)

[0.85761915 0.22328691 0.86003945 0.3477468  0.77015931]


##Empty Array

In [10]:
# Empty are has garbage values when i define it
# Normally it used to create array faster than random and later we overwrite


empty_garabge_value_array = np.empty(5)
print(empty_garabge_value_array)

[0.85761915 0.22328691 0.86003945 0.3477468  0.77015931]


##ND array

In [11]:
# 2D Numpy Array

array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]
