<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
## Array Reshaping and broadcasting

arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [3]:
# Reshape
arr = arr.reshape(5,12)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [4]:
# broadcasting

res = arr + np.array([1,2,3,4,5]).reshape(-1,1)
res

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51],
       [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [5]:
np.array([1,2,3,4,5]).reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
A = np.array([[4, 7, 2], [3, 6, 1], [2, 1, 5]])

det= np.linalg.det(A)
inv_A=np.linalg.inv(A)
print(det)
print(inv_A)

7.000000000000004
[[ 4.14285714 -4.71428571 -0.71428571]
 [-1.85714286  2.28571429  0.28571429]
 [-1.28571429  1.42857143  0.42857143]]


In [7]:
# Vectorize

def my_add(a, b):
  return a + b

vec_add = np.vectorize(my_add)
res =vec_add([1, 2, 3], [4, 5, 6])
res

array([5, 7, 9])

In [8]:
# Filtering

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
