<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/numpy_07_05_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

01. 1D array values: 0-9

In [2]:
arr_0_9=np.arange(10)
arr_0_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.  Full Array (3,3) with true values

In [3]:
arr_true=np.full((3,3),True, dtype=bool)
arr_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Extract even numbers from an array

In [4]:
nums = np.array([0,1,2,3,4,5,6,7,8,9])
only_even = nums[nums%2 == 0]
only_even

array([0, 2, 4, 6, 8])

4.  replace odd with -89

In [5]:
nums = np.array([0,1,2,3,4,5,6,7,8,9])

In [6]:
nums[nums%2 != 0] = -89
nums

array([  0, -89,   2, -89,   4, -89,   6, -89,   8, -89])

5.  1D to 2D ([2][5])

In [7]:
nums = np.array([0,1,2,3,4,5,6,7,8,9])
new_2D = nums.reshape((2,5))

In [8]:
new_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
nums = np.array([0,1,2,3,4,5,6,7,8,9])

# Can be done atomatically
new_2D = nums.reshape(2,-1)
new_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
nums = np.array([0,1,2,3,4,5,6,7,8,9,90,91])

# Can be done atomatically
new_2D = nums.reshape(2,-1)
new_2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 90, 91]])

6.  Stack two arrays vertically in row

In [12]:
# Lets make an array
simple_array = np.arange(10).reshape(2,-1)
simple_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
# another
one_array = np.ones((2,5), dtype=int)
one_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
stacked_v_array = np.vstack((simple_array, one_array))
stacked_v_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
stacked_v_array = np.hstack((simple_array, one_array))
stacked_v_array

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

7. Remove common elements

In [16]:
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

coomon_elements = np.intersect1d(A,B)
coomon_elements

array([2, 4])

8.  Remove common elements from A which are in B

In [17]:
remove_from_A = np.setdiff1d(A,B)
remove_from_A

array([1, 3, 5, 6])