<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_Array_Manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reshaping

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # 3 x 4 array

In [3]:
# Lets Reshape: 2 x 6, 6 x 2, 4 x 3

A_2_6 = A.reshape(2, 6)
A_6_2 = A.reshape(6, 2)
A_4_3 = A.reshape(4, 3)
A_2_6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## Ravel
**Convert Array to 1D**

In [4]:
flatten_A = A.ravel()
flatten_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Flatten

**Works like ravel but make only copy**

In [6]:
A = np.array([[2,3,4],[5,6,7]])
A

array([[2, 3, 4],
       [5, 6, 7]])

In [7]:
A_flatten= A.flatten()
A_flatten

array([2, 3, 4, 5, 6, 7])

## Transpose

In [8]:
A = A.T
A

array([[2, 5],
       [3, 6],
       [4, 7]])

## Concatenation

In [9]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])

C = np.concatenate((A, B), axis=0)
C

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [10]:
D = np.concatenate((A, B), axis=1)
D

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

## vstack, hstack

In [11]:
E = np.vstack((A, B))
E

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [12]:
F = np.hstack((A, B))
F

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

## Spilt

In [13]:
G = np.split(E, 3)
G

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [14]:
G[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
G[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
H = np.split(E, 2, axis=1)
H

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [17]:
H[0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

## Adding new Dimesions

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.shape

(6,)

In [19]:
arr.ndim

1

In [20]:
arr_new_dim=arr[:,np.newaxis]
arr_new_dim

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
arr_new_dim.shape

(6, 1)

## Expend Dimensions

In [22]:
arr_new_dim=np.expand_dims(arr, axis=1) # Same like newaxis but more clear
arr_new_dim

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Squeeze Dimesions

In [23]:
arr_squeezed=np.squeeze(arr_new_dim) # Squeeze upto one dimensions
arr_squeezed

array([1, 2, 3, 4, 5, 6])