<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. import numpy as np and see the version

In [5]:
import numpy as np
np.__version__

'2.0.2'

Question : Create a 1D array of numbers from 0 to 9
Output : array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
val = np.arange(0,10)
val

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Create a boolean array

sol1 = np.full((3,3),True,dtype=bool)
sol1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
sol2= np.full((9),True,dtype=bool).reshape(3,3)
sol2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
sol3 = np.ones((3,3),dtype=bool)
sol3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
sol4 = np.ones((9),dtype=bool).reshape(3,3)
sol4

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
# find all even numbers

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr_even = arr[arr%2==0]
arr_even

array([0, 2, 4, 6, 8])

In [13]:
arr_odd=arr[arr%2==1]
arr_odd

array([1, 3, 5, 7, 9])

In [14]:
arr=np.arange(10)
arr_even = arr[arr%2==0]

In [15]:
arr_even

array([0, 2, 4, 6, 8])

In [16]:
arr[arr%2==0]=-1

In [17]:
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2=arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr2[arr%2==0] = -1

In [21]:
arr2

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [22]:
arr_reshape=arr.reshape(2,-1)
arr_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
arr, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9]))

In [25]:
np.vstack([arr,arr2])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-1,  1, -1,  3, -1,  5, -1,  7, -1,  9]])