<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/Numpy_Day_1_of_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4])

In [2]:
arr_2d = np.array([[1,2,3],[3,4,5]])


In [3]:
arr_1d, arr_2d

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [3, 4, 5]]))

In [4]:
# List vs numpy array

list_1 = [1,2,3,4]
arr_1 = np.array(list_1)

In [5]:
arr_1

array([1, 2, 3, 4])

In [6]:
arr_1*2

array([2, 4, 6, 8])

In [7]:
list_1*2 # repeats

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
# Zeros

zeros_mat =np.zeros((2,5))
zeros_mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# ones
ones_mat =np.ones((2,5))
ones_mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
full_mat = np.full((2,5),6)
full_mat

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [12]:
random_mat= np.random.random((2,3)) # random is a class with random method
random_mat

array([[0.61930005, 0.96306355, 0.53759237],
       [0.94388109, 0.77989501, 0.52557508]])

In [13]:
Zero_to_ten= np.arange(0,10)
Zero_to_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# vector is normal array

vector= np.array([1,2,3])
# matrix is 2d array

matrix = np.array([[1,2,3],[4,5,6]])

# tensor

tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

vector, matrix, tensor

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

In [15]:
matrix.shape, matrix.size, matrix.ndim, matrix.dtype

((2, 3), 6, 2, dtype('int64'))