<a href="https://colab.research.google.com/github/atulnath/numpy-practice/blob/main/numpy_29_05_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

Array_1D = np.array([1,2,3,4])
print(Array_1D)

Array_2D = np.array([[1,2],[3,4]])
print(Array_2D)

#Normal python list

listA= [i for i in range(5)]
print(listA)

print(listA*2) #double the list of items

print(Array_1D*2) # it will multiply the elements by 2


[1 2 3 4]
[[1 2]
 [3 4]]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[2 4 6 8]


# Zeros, Ones, #anyNumber array

In [13]:
zeros= np.zeros((3,4)) # 3 rows and 4 cols

print(zeros)

ones = np.ones((3,4))
print(ones)

seven = np.full((3,4),7)
print(seven)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


#Random

In [15]:
random_val= np.random.random((2,3))

print(random_val)

#sequence
sq = np.arange(0,10,2)

print(sq)

[[0.62052119 0.43313952 0.47815904]
 [0.26113784 0.67178198 0.09908957]]
[0 2 4 6 8]


#vector, mat, tensor

In [16]:
#Vector
Array_1D = np.array([1,2,3,4])
print(Array_1D)
#matrix
Array_2D = np.array([[1,2],[3,4]])
print(Array_2D)
#more than it is called tensor
Array_ND = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(Array_ND)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
